services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: supplysync_db
      POSTGRES_USER: supplysync_user
      POSTGRES_PASSWORD: supplysync_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A supplysync worker -l info
    depends_on:
      - postgres
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: supplysync.settings.development
      DB_NAME: supplysync_db
      DB_USER: supplysync_user
      DB_PASSWORD: supplysync_pass
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      REDIS_CACHE_URL: redis://redis:6379/1

  celery_beat:
    build: .
    command: celery -A supplysync beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - postgres
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: supplysync.settings.development
      DB_NAME: supplysync_db
      DB_USER: supplysync_user
      DB_PASSWORD: supplysync_pass
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      REDIS_CACHE_URL: redis://redis:6379/1

volumes:
  postgres_data:

