ERROR_VALIDATION_FAILED = "VALIDATION_FAILED"
ERROR_RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
ERROR_DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE"
ERROR_INSUFFICIENT_INVENTORY = "INSUFFICIENT_INVENTORY"
ERROR_INVALID_OPERATION = "INVALID_OPERATION"
ERROR_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
ERROR_PERMISSION_DENIED = "PERMISSION_DENIED"
ERROR_NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
ERROR_TOO_MANY_LOGIN_ATTEMPTS = "TOO_MANY_LOGIN_ATTEMPTS"
ERROR_WAREHOUSE_CODE_IMMUTABLE = "WAREHOUSE_CODE_IMMUTABLE"
ERROR_WAREHOUSE_HAS_ACTIVE_INVENTORY = "WAREHOUSE_HAS_ACTIVE_INVENTORY"
ERROR_PO_HAS_NO_ITEMS = "PO_HAS_NO_ITEMS"
ERROR_SELF_APPROVAL_NOT_ALLOWED = "SELF_APPROVAL_NOT_ALLOWED"
ERROR_PO_CANCELLATION_NOT_ALLOWED = "PO_CANCELLATION_NOT_ALLOWED"
ERROR_INSUFFICIENT_STOCK_FOR_ORDER = "INSUFFICIENT_STOCK_FOR_ORDER"
ERROR_SO_CANCELLATION_NOT_ALLOWED = "SO_CANCELLATION_NOT_ALLOWED"

CACHE_KEY_PRODUCTS_LIST = "products:list"
CACHE_KEY_PRODUCTS_DETAIL = "products:detail:{id}"
CACHE_KEY_CATEGORIES_TREE = "categories:tree"
CACHE_KEY_WAREHOUSES_LIST = "warehouses:list"
CACHE_KEY_WAREHOUSES_DETAIL = "warehouses:detail:{id}"
CACHE_KEY_INVENTORY_LOW_STOCK = "inventory:low-stock"
CACHE_KEY_SUPPLIERS_DETAIL = "suppliers:detail:{id}"
CACHE_KEY_REPORTS_DASHBOARD = "reports:dashboard"
CACHE_KEY_PO_SEQUENCE = "po-sequence:{date}"
CACHE_KEY_LOGIN_RATE_LIMIT = "rate-limit:login:{ip_address}"

PRODUCT_CACHE_TTL = 600
CATEGORY_TREE_CACHE_TTL = 1800
WAREHOUSE_CACHE_TTL = 900
LOW_STOCK_CACHE_TTL = 300
SUPPLIER_CACHE_TTL = 1200
REPORT_CACHE_TTL = 600
LOGIN_RATE_LIMIT_TTL = 900
PO_SEQUENCE_TTL = 86400

LOGIN_RATE_LIMIT_MAX_ATTEMPTS = 5

CODE_PREFIX_WAREHOUSE = "WH"
CODE_PREFIX_CATEGORY = "CAT"
CODE_PREFIX_SKU = "SKU"
CODE_PREFIX_SUPPLIER = "SUP"
CODE_PREFIX_PURCHASE_ORDER = "PO"
CODE_PREFIX_TRANSFER = "TRANSFER"
CODE_PREFIX_SALES_ORDER = "SO"

SHORT_CODE_LENGTH = 6
SKU_RANDOM_LENGTH = 8
PO_DATE_FORMAT = "%Y%m%d"
LOGIN_PATH = "/api/v1/auth/login/"

EVENT_INVENTORY_UPDATED = "EVENT [inventory-updated]: product_id=%s, warehouse_id=%s, type=%s, qty=%s"
EVENT_INVENTORY_TRANSFER = "EVENT [inventory-transfer-initiated]: product_id=%s, from=%s, to=%s, qty=%s"
EVENT_PO_RECEIVED = "EVENT [purchase-order-received]: po_id=%s, received_by=%s"
EVENT_SO_CREATED = "EVENT [sales-order-created]: order_id=%s, created_by=%s"
EVENT_SO_CANCELLED = "EVENT [sales-order-cancelled]: order_id=%s"
LOW_STOCK_LOG = "LOW STOCK ALERT: Product %s in Warehouse %s has %s units remaining (reorder level: %s)"
DAILY_SUMMARY_LOG = (
    "DAILY SUMMARY: Date=%s, New POs=%s, POs Received=%s, "
    "New Sales Orders=%s, Orders Dispatched=%s, Orders Delivered=%s"
)

